export {default as 商品分类} from './商品分类'
export {default as 商品列表} from './商品列表'
export {default as 商品详情页} from './商品详情页'
export {default as 成就} from './成就'
export {default as 我} from './我'
export {default as 收藏夹} from './收藏夹'
export {default as 新品榜} from './新品榜'
export {default as 更多} from './更多'
export {default as 热销榜} from './热销榜'
export {default as 物流信息} from './物流信息'
export {default as 积分} from './积分'
export {default as 购物车} from './购物车'
export {default as 飙升榜} from './飙升榜'
export {default as 首页} from './首页'

