export {default as 首页} from './0_首页'
export {default as 商品分类} from './0-1_商品分类'
export {default as 新品榜} from './0-2_新品榜'
export {default as 热销榜} from './0-3_热销榜'
export {default as 飙升榜} from './0-4_飙升榜'
export {default as 更多} from './0-5_更多'
export {default as 我} from './1_我'
export {default as 成就面板} from './1-1_成就面板'
export {default as 收藏面板} from './1-2_收藏面板'
export {default as 物流面板} from './1-3_物流面板'
export {default as 积分面板} from './1-4_积分面板'
export {default as 购物车} from './2_购物车'

