export {default as 首页} from './首页'
export {default as 商品分类} from './商品分类'
export {default as 新品榜} from './新品榜'
export {default as 热销榜} from './热销榜'
export {default as 飙升榜} from './飙升榜'
export {default as 更多} from './更多'
export {default as 我} from './我'
export {default as 购物车} from './购物车'
export {default as 商品详情页} from './商品详情页'

